### ISSUE TITLE
Different behaviour in REPL and IJulia

### ISSUE THREAD

**Issue by rened** [kmsquire/Match.jl#14]
I absolutely do not understand how this can be, or where to start looking. Executing the following snippet shows `f(3) => "no match"` in the REPL, but shows `f(3) => nothing` in IJulia.
```jl
using Match
@show VERSION
f(x) = @match x begin
    1 => "one"
    _ => "no match"
end
@show f(1)
@show f(3)
```
Running julia 0.3.3, Ijulia 0.1.16, Match 0.0.5

**Comment by kmsquire** [comment]
Okay, sorry for the slow response here.  Here's what I've found so far:

First, `_` is a valid variable name, and for some reason, it's defined as `nothing` in IJulia:

```julia
In [1]: _ == nothing
Out[1]: true
```

but not defined as anything at the terminal.

```julia
julia> _ == nothing
ERROR: UndefVarError: _ not defined
```

I'm not sure why that is...

Even though that is true, it should probably still be recognized as a variable by `Match.jl`, so it's still a bug.

Just to complete this, at the REPL (this is correct):

```julia
julia> macroexpand(:(@match x begin
           1 => "one"
           _ => "no match"
       end))
quote  # none, line 2:
    if Match.ismatch(1,x) # line 408:
        "one"
    else  # line 410:
        begin  # line 3:
            "no match"
        end
    end
end
```
but in IJulia (incorrect):
```julia
In [3]: macroexpand(:(@match x begin
    1 => "one"
    _ => "no match"
end))

Out[3]: quote  # In[3], line 2:
    if Match.ismatch(1,x) # line 408:
        "one"
    else  # line 410:
        begin  # line 3:
            if Match.ismatch(_,x) # line 408:
                "no match"
            else  # line 410:
                nothing
            end
        end
    end
end
```

**Comment by rened** [comment]
I found that IJulia apparently sets `_`, `__` and `___` to the last three execution results. Would it be possible to ignore this in Match.jl to still be able to use `_` for the catch-all?

**Comment by kmsquire** [comment]
@stevengj, just curious: why does `_ == nothing` in IJulia?

**Comment by kmsquire** [comment]
Sorry, @stevengj, you can ignore my message--I missed the previous message from @rened when I posted.

@rened, it should be possible, but I'm not sure when I'll get to it.  I'll try to do so soon (for some small value of "soon").

**Comment by rened** [comment]
Thanks a lot, no rush. If I get time I'll try to look into this as well.

**Comment by kmsquire** [comment]
Sounds good.

**Comment by stevengj** [comment]
@kmsquire, I was following IPython's history variables.  To be honest, I haven't become a big fan of these; I'm inclined to ditch them and just have `ans` (like the REPL) and `Out[n]`.

**Comment by rened** [comment]
Thanks for fixing this! `@match` is really handy.

**Comment by kmsquire** [comment]
Sorry it took so long, but glad you find it useful!
