### ISSUE TITLE
[PkgEval] Match may have a testing issue on Julia 0.3 (2015-04-01)

### ISSUE THREAD

**Issue by IainNZ** [kmsquire/Match.jl#18]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.3
* On **2015-03-30** the testing status was `Tests pass.`
* On **2015-04-01** the testing status changed to `Package doesn't load.`

`Tests pass.` means that PackageEvaluator found the tests for your package, executed them, and they all passed.

`Package doesn't load.` means that PackageEvaluator did not find tests for your package. Additionally, trying to load your package with `using` failed.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("Match")' log
INFO: Cloning cache of Match from git://github.com/kmsquire/Match.jl.git
INFO: Installing Compat v0.3.6
INFO: Installing Match v0.1.1
INFO: Package database updated

>>> 'using Match' log
ERROR: ArrayViews not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/testpkg/v0.3/Match/src/matchutils.jl, in expression starting on line 5
while loading /home/vagrant/testpkg/v0.3/Match/src/Match.jl, in expression starting on line 9
while loading /vagrant/releaseMZ/PKGEVAL_Match_using.jl, in expression starting on line 4
Julia Version 0.3.6
Commit 0c24dca (2015-02-17 22:12 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
/home/vagrant/testpkg/v0.3/Match


>>> test log
no tests to run
>>> end of log
```

**Comment by kmsquire** [comment]
Whoops--forgot to update REQUIRE file!  Will be fixed momentarily.

@IainNZ, thanks loads for running this service!

**Comment by kmsquire** [comment]
Should be fixed now, according to pkg.julialang.org
