### ISSUE TITLE
Match.jl doesn't work in Julia 0.6

### ISSUE THREAD

**Issue by jamii** [kmsquire/Match.jl#35]
It looks like the representation of infix operators changed.

``` julia
jamie@machine:~$ julia-0.5/bin/julia
julia> :(x => x).head
:(=>)

jamie@machine:~$ julia-0.6/bin/julia
julia> :(x => x).head
:call
```

**Comment by kmsquire** [comment]
Thanks. Should be a straightforward fix, but not sure if I can get to it soon. Are you up to making a PR?

**Comment by jamii** [comment]
Not any time soon, but it'll go on the todo list.

**Comment by kmsquire** [comment]
I've started working on this (see #36).  The above issue is fixed on that branch, but tests don't pass yet.

**Comment by jamii** [comment]
Awesome, thanks :)

**Comment by kmsquire** [comment]
Latest tagged version should be working in Julia v0.6. Let me know if you run into any problems.

**Comment by jamii** [comment]
Yep, moved everything to Julia 0.6 and it's all working nicely. Thanks for the update.

**Comment by kmsquire** [comment]
👍
