### ISSUE TITLE
Dropped support for Char ranges

### ISSUE THREAD

**Issue by aviks** [kmsquire/Match.jl#51]
Has there been some change in the way ranges behave in 1.0? The following code returns `true` in Match.jl `v0.4.0` but returns `false` in `v1.0.0` for `ch = ' '`

```julia
@match ch begin
       '\u0000':'\u0040' || '\u005B':'\u0060' || '\u007B':'\u007E' => true
       _ => false
end
```

**Comment by kmsquire** [comment]
No reason, just an oversight on my part. Can you open a PR with a test?

**Comment by kmsquire** [comment]
@aviks, actually, I'm going to work on this right now.

**Comment by kmsquire** [comment]
See #52

**Comment by aviks** [comment]
Thanks! Sorry i couldn't get to that today, was planning to in a day or two. Thanks for taking care of this.

**Comment by kmsquire** [comment]
No worries—it was an easy fix, and I found a few minutes to work on it. Cheers!
