### ISSUE TITLE
use `false` instead of `Symbol(false)`

### ISSUE THREAD

**Issue by JeffBezanson** [kmsquire/Match.jl#58]
See https://github.com/JuliaLang/julia/pull/34077#issuecomment-565172774

Symbols named `false` used to round-trip incorrectly; they would be converted to Bool at some point. This is now fixed. `false` can be placed in an AST directly; it doesn't need to be a Symbol.

**Comment by JeffBezanson** [comment]
https://github.com/kmsquire/Match.jl/blob/98f305c62ae6d03e4f65033d038a23d568589c24/src/matchmacro.jl#L112

**Comment by kmsquire** [comment]
What version of Julia should changing this require?

**Comment by JeffBezanson** [comment]
Replacing `Symbol(false)` with `false` should work on all versions.

**Comment by vtjnash** [comment]
Presumably this is why PkgEval is failing:
```
Error During Test at /home/pkgeval/.julia/packages/Match/qiTCM/test/matchtests.jl:303
  Test threw exception
  Expression: balance(Black(1, Red(2, Red(3, Leaf(), Leaf()), Leaf()), Leaf())) == Red(2, Black(3, Leaf(), Leaf()), Black(1, Leaf(), Leaf()))
  UndefVarError: false not defined
  Stacktrace:
   [1] balance(tree::Black)
     @ Main ~/.julia/packages/Match/qiTCM/test/matchtests.jl:294
```

**Comment by kmsquire** [comment]
Sorry, I forgot all about this.
